In [1]:
import sys
from pathlib import Path

import pandas as pd

In [2]:
PROJECT_ROOT = Path.cwd().parent

print(PROJECT_ROOT)

d:\Project-root\SKIT-IOT-2023-2027-F-031

In [3]:
CICIDS_PATH = Path(
    r"D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017"
)

CIC_IOT_PATH = Path(
    r"D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CIC-IoT2023"
)

In [4]:
sys.path.append(str(PROJECT_ROOT))

from ml.data.load_dataset import load_csv, load_dataset_folder

In [5]:
cicids_files = sorted(CICIDS_PATH.glob("*.csv"))

print("Number of CSV files:", len(cicids_files))

print("First file:", cicids_files[0].name)

Number of CSV files: 8
First file: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv

In [6]:
sample_cicids = load_csv(cicids_files[0])

print("Shape:", sample_cicids.shape)
sample_cicids.head()

Shape: (225745, 79)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [7]:
iot_files = sorted(CIC_IOT_PATH.rglob("*.csv"))

print("Number of files:", len(iot_files))

print("First file:", iot_files[0].name)

Number of files: 309
First file: Backdoor_Malware.pcap.csv

In [8]:
sample_iot = load_csv(iot_files[0])

print("Shape:", sample_iot.shape)
sample_iot.head()

Shape: (3218, 39)

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,13.2,17,111.8,21.654112,0.0,0.0,0.0,0.0,0.3,0.0,...,0.9,2105,60,1392,210.5,415.549502,210.5,0.046181,10,172681.388889
1,11.2,17,63.5,134.621809,0.0,0.1,0.0,0.0,0.0,0.0,...,1.0,4736,60,1392,473.6,632.696206,473.6,0.008186,10,400304.488889
2,13.6,17,65.6,211.662495,0.0,0.1,0.0,0.0,0.2,0.0,...,1.0,3788,62,1392,378.8,508.763381,378.8,0.004735,10,258840.177778
3,24.8,6,84.4,155.707333,0.0,0.0,0.0,0.4,0.7,0.0,...,1.0,2917,62,833,291.7,308.737951,291.7,0.006422,10,95319.122222
4,10.4,17,118.3,105.440687,0.0,0.0,0.0,0.0,0.1,0.0,...,1.0,1163,62,230,116.3,75.052648,116.3,0.009484,10,5632.900000

In [9]:
cicids2017 = load_dataset_folder(
    CICIDS_PATH,
    dataset_name="CICIDS2017"
)

Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Friday-WorkingHours-Morning.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Monday-WorkingHours.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Tuesday-WorkingHours.pcap_ISCX.csv
Loading: D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CICIDS2017\Wednesday-workingHours.pcap_ISCX.csv

In [10]:
print("CICIDS2017 shape:", cicids2017.shape)
cicids2017.head()

CICIDS2017 shape: (2830743, 81)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Source_File,Dataset
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,0.0,0,0,0.0,0.0,0,0,BENIGN,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,CICIDS2017
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,0.0,0,0,0.0,0.0,0,0,BENIGN,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,CICIDS2017
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,0.0,0,0,0.0,0.0,0,0,BENIGN,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,CICIDS2017
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,0.0,0,0,0.0,0.0,0,0,BENIGN,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,CICIDS2017
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,0.0,0,0,0.0,0.0,0,0,BENIGN,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,CICIDS2017

In [11]:
cicids2017["Source_File"].value_counts()

Source_File
Wednesday-workingHours.pcap_ISCX.csv                           692703
Monday-WorkingHours.pcap_ISCX.csv                              529918
Tuesday-WorkingHours.pcap_ISCX.csv                             445909
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv    288602
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv           286467
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv               225745
Friday-WorkingHours-Morning.pcap_ISCX.csv                      191033
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv         170366
Name: count, dtype: int64

In [12]:
cicids2017["Dataset"].value_counts()

Dataset
CICIDS2017    2830743
Name: count, dtype: int64

In [13]:
cicids2017.columns.tolist()

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 ' Label',
 'Source_File',
 'Dataset']

In [19]:
cic_iot2023_path = iot_files[0]

print("Testing file:")
print(cic_iot2023_path)

cic_iot2023 = load_csv(cic_iot2023_path)

print("Shape:", cic_iot2023.shape)
print("\nColumns:")
print(cic_iot2023.columns.tolist())

cic_iot2023.head()
cic_iot2023.dtypes.value_counts()
cic_iot2023.iloc[:, -1].value_counts()

Testing file:
D:\Project-root\SKIT-IOT-2023-2027-F-031\data\raw\CIC-IoT2023\Backdoor_Malware\Backdoor_Malware.pcap.csv
Shape: (3218, 39)

Columns:
['Header_Length', 'Protocol Type', 'Time_To_Live', 'Rate', 'fin_flag_number', 'syn_flag_number', 'rst_flag_number', 'psh_flag_number', 'ack_flag_number', 'ece_flag_number', 'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count', 'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP', 'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max', 'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Variance']

Variance
0.000000         227
203918.400000     12
475809.600000      7
52272.900000       7
3.600000           6
                ...
24417.877778       1
4231.822222        1
5323.388889        1
4142.266667        1
2778.696429        1
Name: count, Length: 2901, dtype: int64

In [20]:
from ml.data.load_dataset import validate_dataset
validate_dataset(cicids2017)
validate_dataset(cic_iot2023)

Rows: 2830743
Columns: 81

Duplicate rows: 256479

Missing values: 1358
Infinite values: 4376

Data types:
int64      54
float64    24
object      3
Name: count, dtype: int64
Rows: 3218
Columns: 39

Duplicate rows: 3

Missing values: 0
Infinite values: 0

Data types:
float64    30
int64       9
Name: count, dtype: int64

True